name: quests
description: Nurse quests
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2

dev_dependencies:
  dart_code_metrics: ^5.7.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: ^2.1.0

flutter:
  uses-material-design: false
  assets:
    - assets/data.json
